-- Pause Menu Items
PAUSE_MENU_SETTINGS = 1
PAUSE_MENU_QUIT = 2

-- Settings Menu Items
SETTINGS_MENU_VOLUME = 3
SETTINGS_MENU_LANGUAGE = 4
SETTINGS_MENU_CONTROLS = 5

-- Possible states
STATE_PLAYING = 1
STATE_PAUSED = 2

--Menus
MENUS_MAIN_PAUSE = 1
MENUS_SETTINGS=2
MENUS_LANGUAGE=3